[
   {
      "document":{
         "id":353,
         "name":"Polymethyl Methacrylate (PMMA) - Experiment",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2021-07-14T14:35:49.3849971Z"
   },
   {
      "document":{
         "id":353,
         "name":"Polymethyl Methacrylate (PMMA) - Experiment",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2021-07-14T13:55:46.2221718Z"
   },
   {
      "document":{
         "id":353,
         "name":"Polymethyl Methacrylate (PMMA) - Experiment",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2021-07-14T13:41:13.2374282Z"
   },
   {
      "document":{
         "id":353,
         "name":"Polymethyl Methacrylate (PMMA) - Experiment",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2021-07-14T13:35:49.8374647Z"
   },
   {
      "document":{
         "id":353,
         "name":"Polymethyl Methacrylate (PMMA) - Experiment",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2021-07-14T13:25:37.0683698Z"
   },
   {
      "document":{
         "id":353,
         "name":"Polymethyl Methacrylate (PMMA) - Experiment",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2021-07-14T13:18:52.5413047Z"
   },
   {
      "document":{
         "id":353,
         "name":"Polymethyl Methacrylate (PMMA)",
         "type":11
      },
      "action":0,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2021-07-14T13:18:19.3756813Z"
   },
   {
      "document":{
         "id":321,
         "name":"Water",
         "type":11
      },
      "action":4,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2021-06-04T10:42:38.724197Z"
   },
   {
      "document":{
         "id":322,
         "name":"SediTest (PMMA 15 - 40 µm)",
         "type":11
      },
      "action":4,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2021-06-04T10:42:38.724197Z"
   },
   {
      "document":{
         "id":77,
         "name":"BCR Quartz 70",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2020-12-14T10:28:18.0728934Z"
   },
   {
      "document":{
         "id":77,
         "name":"BCR Quartz 70",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2020-12-14T10:28:17.0708866Z"
   },
   {
      "document":{
         "id":290,
         "name":"test",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2020-07-09T09:39:30.2110586Z"
   },
   {
      "document":{
         "id":290,
         "name":"test",
         "type":11
      },
      "action":0,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2020-07-09T09:39:19.6000971Z"
   },
   {
      "document":{
         "id":161,
         "name":"Water",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2020-07-06T14:01:42.2486665Z"
   },
   {
      "document":{
         "id":289,
         "name":"test",
         "type":11
      },
      "action":3,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2020-07-06T10:43:36.400859Z"
   },
   {
      "document":{
         "id":289,
         "name":"test",
         "type":11
      },
      "action":0,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2020-07-06T10:43:20.6367756Z"
   },
   {
      "document":{
         "id":24,
         "name":"Aluminum Silicate (Silimanite)",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2020-04-21T14:00:56.2450862Z"
   },
   {
      "document":{
         "id":24,
         "name":"Aluminum Silicate (Silimanite)",
         "type":11
      },
      "action":1,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2020-04-21T14:00:54.9822303Z"
   },
   {
      "document":{
         "id":257,
         "name":"SediTest (PMMA 15 - 40 µm)",
         "type":11
      },
      "action":4,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2019-11-28T11:53:50.7919233Z"
   },
   {
      "document":{
         "id":225,
         "name":"Aluminum Silicate (Silimanite)",
         "type":11
      },
      "action":0,
      "author":{
         "displayName":"Administrator",
         "username":"admin"
      },
      "time":"2019-09-09T07:18:42.8346648Z"
   }
]
